language: python
services:
  - docker
stages:
  - name: deploy
    if: branch = master
python:
- '3.6'
before_install:
  - echo $DOCKERHUB_PSSWORD | docker login docker -u ${DOCKERHUB_USERNAME} --password-stdin
  - pip install docker-compose
install:
  - docker-compose build
script:
  - docker-compose push
