language: python
services:
  - docker
stages:
  - name: deploy
    if: branch = master
python:
- '3.6'
before_install:
  - docker-comose pull
install:
  - docker-compose build
script:
  - docker login docker -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
#  - docker-compose push
