language: python
services:
  - docker
stages:
  - name: deploy
    if: branch = master
python:
- '3.6'
install:
  - docker-compose build
deploy:
  - docker login docker -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  - docker-compose push
