language: python
services:
  - docker
stages:
  - name: docker_push
    if: branch = master
before_install:
  - pip install docker-compose
install:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - docker-compose pull --ignore-pull-failures
  - docker-compose build
jobs:
  include:
    - stage: docker_push
      script:
        - docker-compose push
        - export IMPROV_GUIDE_VERSION=latest && docker-compose build
        - export IMPROV_GUIDE_VERSION=latest && docker-compose push
notifications:
  slack:
    rooms:
    - improvguide:WGB9wPwKNlQkDP4nwB4FfYbq#alerts
git:
  submodules: false
