language: python
services:
  - docker
stages:
  - name: docker_build
  - name: docker_push
    if: branch = master
python:
- '3.6'
before_install:
  - pip install docker-compose
jobs:
  include:
    - stage: docker_build
      script: docker-compose build
    - stage: docker_push
      script:
        - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - docker-compose push
notifications:
  slack:
    rooms:
    - improvguide:WGB9wPwKNlQkDP4nwB4FfYbq#general
git:
  submodules: false
