language: python
services:
  - docker
stages:
  - name: deploy
    if: branch = master
python:
- '3.6'
before_install:
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PSSWORD}
  - pip install docker-compose
install:
  - docker-compose build
script:
  - docker-compose push
