version: '3.7'

#  ./static:/src/uk-improv-guide/static

services:

  nginx:
    image: "salimfadhley/uk-improv-guide-nginx:${IMPROV_GUIDE_VERSION}"
    build:
      context: .
      target: uk-improv-guide-nginx
    volumes:
      - media:/usr/share/nginx/html/media:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    depends_on:
      - site
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  site:
    image: "salimfadhley/uk-improv-guide:${IMPROV_GUIDE_VERSION}"
    build:
      context: .
      target: uk-improv-guide
    volumes:
      - media:/src/uk_improv_guide/static/media
    working_dir: "/src/uk_improv_guide"
    ports:
      - "80:80"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      SLACK_WEB_HOOK: ${SLACK_WEB_HOOK}
      PRODUCTION_SECRET: ${PRODUCTION_SECRET}
      SITE_PORT: ${SITE_PORT}
    networks:
      - internal

volumes:
  media:

networks:
  internal: