version: '3.7'

services:
  nginx:
    image: "salimfadhley/uk-improv-guide-nginx:${IMPROV_GUIDE_VERSION}"
    build:
      context: .
      target: uk-improv-guide-nginx
    volumes:
      - media:/usr/share/nginx/html/media:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    depends_on:
      - site
    deploy:
      placement:
        constraints:
          - node.role == manager

  site:
    image: "salimfadhley/uk-improv-guide:${IMPROV_GUIDE_VERSION}"
    build:
      context: .
      target: uk-improv-guide
    volumes:
      - media:/media
      - backup:/backup
      - ssh:/root/.ssh
    working_dir: "/src/uk_improv_guide"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      SLACK_WEB_HOOK: ${SLACK_WEB_HOOK}
      PRODUCTION_SECRET: ${PRODUCTION_SECRET}
      SITE_PORT: ${SITE_PORT}
      BACKUP_DIR: /backup
    networks:
      - internal

volumes:
  media:
  ssh:
  backup:

networks:
  internal: