version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

x-base-database: &base-database
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  SLACK_WEB_HOOK: ${SLACK_WEB_HOOK}
  PRODUCTION_SECRET: ${PRODUCTION_SECRET}

x-base-image: &base-image
  image: "salimfadhley/uk-improv-guide:${IMPROV_GUIDE_VERSION}"

services:

  python:
    <<: *base-image
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      <<: *base-database
    networks:
      - internal

  bash:
    <<: *base-image
    entrypoint: ["/bin/bash"]
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      <<: *base-database
    networks:
      - internal

  db:
    <<: *base-dev
    image: postgres:10.9
    container_name: "postgres"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: '5432'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal: