version: '3.7'

services:
  nginx:
    image: "salimfadhley/uk-improv-guide-nginx:${IMPROV_GUIDE_VERSION}"
    build:
      context: .
      target: uk-improv-guide-nginx
    container_name: production_nginx
    volumes:
      - static:/usr/share/nginx/html/static:ro
    ports:
      - 81:80
      - 443:443
    networks:
      - internal
    depends_on:
      - prod

  prod:
    image: "salimfadhley/uk-improv-guide:${IMPROV_GUIDE_VERSION}"

    volumes:
      - static:/src/uk-improv-guide/static
    working_dir: "/src/uk-improv-guide"
    entrypoint: ["gunicorn", "--bind=0.0.0.0:80", "uk-improv-guide.wsgi"]
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      SLACK_WEB_HOOK: ${SLACK_WEB_HOOK}
      PRODUCTION_SECRET: ${PRODUCTION_SECRET}
      SITE_PORT: ${SITE_PORT}
    networks:
      - internal

  db:
    image: postgres:10.9
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal

volumes:
  static:
    postgres_data:

networks:
  internal: