version: '3.7'

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    depends_on:
      - prod