version: '3.7'

services:
  nginx:
    image: "salimfadhley/uk-improv-guide-nginx:${IMPROV_GUIDE_VERSION}"
    build:
      context: .
      target: uk-improv-guide-nginx
    container_name: production_nginx
    volumes:
      - static:/usr/share/nginx/html/static:ro
    ports:
      - 81:80
      - 443:443
    networks:
      - internal
    depends_on:
      - prod

  db:
    image: postgres:10.9
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal

volumes:
  static:
    postgres_data:

networks:
  internal: