version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

x-common_settings: &common
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  SLACK_WEB_HOOK: ${SLACK_WEB_HOOK}
  DEBUG: "Yes"
  PRODUCTION_SECRET: ${PRODUCTION_SECRET}
x-base-image: &base-image
  image: "salimfadhley/uk_improv_guide:${IMPROV_GUIDE_VERSION}"
  build:
    context: .
    target: uk_improv_guide


services:

  dev:
    <<: *base-dev
    <<: *base-image

    volumes:
      - ./src:/src
      - ./static:/src/uk_improv_guide/static
    working_dir: "/src/uk_improv_guide"
    entrypoint: ["/src/uk_improv_guide/start_dev.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      <<: *common
      SITE_PORT: ${SITE_PORT}
    networks:
      - internal

  adminer:
    image: adminer:4.7.1
    container_name: "dev_adminer"
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "db"
    depends_on:
      - db
    networks:
      - internal


  python:
    <<: *base-image
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      <<: *common
    networks:
      - internal

  portainer:
    <<: *base-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: portainer/portainer
    ports:
      - "9000:9000"

networks:
  internal:

volumes:
  portainer_data:
