version: '3.7'

services:
  nginx:
    image: "salimfadhley/uk-improv-guide-nginx:${IMPROV_GUIDE_VERSION}"
    build:
      context: .
      target: uk-improv-guide-nginx
    container_name: production_nginx
    volumes:
      - static:/usr/share/nginx/html/static:ro
    ports:
      - 81:80
      - 443:443
    networks:
      - internal
#    depends_on:
#      - prod

volumes:
  static:

networks:
  internal: