version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

x-common_settings: &common
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  SLACK_WEB_HOOK: ${SLACK_WEB_HOOK}
  DEBUG: "Yes"
  PRODUCTION_SECRET: ${PRODUCTION_SECRET}
x-base-image: &base-image
  image: "salimfadhley/uk-improv-guide:${IMPROV_GUIDE_VERSION}"
  build:
    context: .
    target: uk-improv-guide


services:

  dev:
    <<: *base-dev
    <<: *base-image

    volumes:
      - ./src:/src
      - ./static:/src/uk-improv-guide/static
    working_dir: "/src/uk-improv-guide"
    entrypoint: ["/src/uk-improv-guide/start_dev.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      <<: *common
      SITE_PORT: ${SITE_PORT}
    networks:
      - internal

  adminer:
    image: adminer:4.7.1
    container_name: "dev_adminer"
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "db"
    depends_on:
      - db
    networks:
      - internal


  python:
    <<: *base-image
    volumes:
      - ./src:/src
    depends_on:
      - db
    environment:
      <<: *common
    networks:
      - internal

  nginx:
    image: salimfadhley/uk-improv-guide-nginx:0.0.1
    build:
      context: .
      target: uk-improv-guide-nginx

networks:
  internal: