# Generated by Django 2.2.1 on 2019-05-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('facebook_link', models.CharField(max_length=100)),
                ('contact_email_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('facebook_link', models.CharField(max_length=256)),
                ('website_link', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('facebook_link', models.CharField(max_length=100, null=True)),
                ('contact_email_address', models.CharField(max_length=100, null=True)),
                ('players', models.ManyToManyField(to='uk_improv_guide.Performer', verbose_name='teams playing')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('S', 'Show'), ('J', 'Jam'), ('W', 'Workshop'), ('A', 'Audition')], max_length=1)),
                ('start_time', models.DateTimeField()),
                ('facebook_link', models.CharField(max_length=256)),
                ('eventbrite_link', models.CharField(max_length=256)),
                ('teams', models.ManyToManyField(to='uk_improv_guide.Team', verbose_name='teams playing')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uk_improv_guide.Venue')),
            ],
        ),
    ]
