# Generated by Django 3.0.3 on 2020-02-28 10:00

import django.db.models.deletion
import django_countries.fields
import uk_improv_guide.lib.adminable
import uk_improv_guide.lib.site_mappable
import uk_improv_guide.lib.slack_notification_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uk_improv_guide", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    django_countries.fields.CountryField(default="GB", max_length=2),
                ),
                ("image", models.ImageField(blank=True, upload_to="city/")),
            ],
            options={"verbose_name_plural": "Cities", "ordering": ["name"],},
            bases=(
                uk_improv_guide.lib.slack_notification_mixin.SlackNotificationMixin,
                uk_improv_guide.lib.site_mappable.SiteMapThing,
                uk_improv_guide.lib.adminable.AdminableObject,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="city_obj",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="uk_improv_guide.City",
                verbose_name="City",
            ),
        ),
    ]
