# Generated by Django 2.2.4 on 2019-08-02 21:32

import django.db.models.deletion
import uk_improv_guide.lib.adminable
import uk_improv_guide.lib.site_mappable
import uk_improv_guide.lib.slack_notification_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("uk_improv_guide", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_link", models.URLField(blank=True, max_length=256)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="course/")),
                ("start_time", models.DateTimeField(verbose_name="Show start time")),
                (
                    "lesson_duration",
                    models.FloatField(verbose_name="Lesson duration in hours"),
                ),
                (
                    "number_of_lessons",
                    models.IntegerField(verbose_name="Total number of lessons"),
                ),
                (
                    "class_show",
                    models.BooleanField(verbose_name="Includes a class show"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uk_improv_guide.School",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uk_improv_guide.Performer",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uk_improv_guide.Venue",
                    ),
                ),
            ],
            options={"ordering": ["-start_time"]},
            bases=(
                uk_improv_guide.lib.slack_notification_mixin.SlackNotificationMixin,
                uk_improv_guide.lib.site_mappable.SiteMapThing,
                uk_improv_guide.lib.adminable.AdminableObject,
                models.Model,
            ),
        )
    ]
