# Generated by Django 2.2.4 on 2019-08-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("uk_improv_guide", "0002_course")]

    operations = [
        migrations.RemoveField(model_name="course", name="website_link"),
        migrations.AddField(
            model_name="course",
            name="course_link",
            field=models.URLField(
                blank=True,
                help_text="A web page where students can find out more about this course, and book.",
                max_length=256,
                verbose_name="Course Booking URL",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="lesson_duration",
            field=models.FloatField(
                help_text="How long is each lesson? Write the answer in decimal, for example two and a half hours should be written as 2.5.",
                verbose_name="Lesson duration in hours",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                help_text="The name of your course, but without the school name or any branding.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="number_of_lessons",
            field=models.IntegerField(
                help_text="The total mumber of lessons in this course.",
                verbose_name="Total number of lessons",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                help_text="Which school is offering this course?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="uk_improv_guide.School",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_time",
            field=models.DateTimeField(verbose_name="First class start time"),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="This selection box includes performers who teach at at least one school.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="uk_improv_guide.Performer",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="venue",
            field=models.ForeignKey(
                help_text="Where will this clas be taught?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uk_improv_guide.Venue",
            ),
        ),
    ]
