# Generated by Django 3.0.3 on 2020-02-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uk_improv_guide", "0002_auto_20200228_1000"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name", "country"], "verbose_name_plural": "Cities"},
        ),
    ]
