# Generated by Django 3.0.3 on 2020-03-03 23:00

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uk_improv_guide", "0004_auto_20200228_2120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="city",
            field=models.CharField(default="London", editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name="venue",
            name="country",
            field=django_countries.fields.CountryField(
                default="GB", editable=False, max_length=2
            ),
        ),
    ]
