# Generated by Django 2.2.4 on 2019-08-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("uk_improv_guide", "0005_event_duration")]

    operations = [
        migrations.RemoveField(model_name="festival", name="venue"),
        migrations.AddField(
            model_name="festival",
            name="venues",
            field=models.ManyToManyField(blank=True, to="uk_improv_guide.Venue"),
        ),
        migrations.AlterField(
            model_name="festival",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uk_improv_guide.School",
            ),
        ),
    ]
