# Generated by Django 2.2.4 on 2019-08-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_improv_guide', '0008_auto_20190811_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='special_guests',
            field=models.ManyToManyField(blank=True, related_name='guesting', to='uk_improv_guide.Performer'),
        ),
    ]
